### ISSUE TITLE
Button.Image and ToolbarItem.Icon?

### ISSUE THREAD

**Issue by rraallvv** [muak/SvgImageSource#2]
Does `SvgImageSource` support `Button.Image` and `ToolbarItem.Icon`?

**Comment by muak** [comment]
@rraallvv 
I'm sorry that this library doesn't support ToolbarItem.Icon and Button.Image because Xamarin.Forms defines those properties as FileImageSource.
SvgImageSource must be used by a property defined as ImageSource on Xamarin.Forms.

I hope that Xamarin.Forms will change FileImageSource To ImageSource.

**Comment by rraallvv** [comment]
@muak thanks for your quick reply.

Is there a way with SvgImageSource to convert SVG images to PNG or JPG an store them somewhere in the filesystem?

I'm asking because I was able to make ToolbarItem.Icon to load a rasterized file stored in the cache, and Button.Image has the problem that it only accepts drawables or resources, but using a custom renderer that limitation could be circumvented too.

**Comment by muak** [comment]
@rraallvv 
SvgImageSource hasn't  the function converting an image.
But an SVG image can be converted to PNG/JPG and save it on each platform.
I have ever considered saving as png/jpg files once such as what you said.
However, thinking performance, I became to think it better that we use png/jpg files from the beginning.

**Comment by rraallvv** [comment]
@muak  it seems trying to handle SVG image as resources and rasterizing when it's needed isn't worth it, thanks for pointing that out.

I finally settled for a [NuGet package](https://github.com/Redth/Resizetizer) to build all PNG files from SVG images. It has the benefit that SVG files aren't shipped with the application.

**Comment by muak** [comment]
@rraallvv 
That package is very good!
It is a nice idea that png/jpg images are created and arranged when building.
I think that I will try it too!

Thank you.
