### ISSUE TITLE
Display SVG image from URL

### ISSUE THREAD

**Issue by himanshudwd765** [muak/SvgImageSource#3]
How to display the SVG image from the url. I tried this:

Image = SvgImageSource.FromSvg("https://baseurl/endpoint/imageName.svg");

It's not working.

**Comment by muak** [comment]
@himanshudwd765 

I regret to say that it is not supported loading an SVG from URL.
This is only supported loading from a local resource file.

But I consider implementing the function that loads from URL stream.

Thank you.

**Comment by torshid** [comment]
Any news?

**Comment by candidodmv** [comment]
Any news +1?

**Comment by muak** [comment]
@torshid 
@candidodmv 

URL support is available in the current prerelease version.

https://www.nuget.org/packages/Xamarin.Forms.Svg/

Thanks.

**Comment by candidodmv** [comment]
Thank you! I will checkout and givi you a feedback, asap !

**Comment by candidodmv** [comment]
@muak I've tested the URL support and it's working pretty well. Thank you so much!

**Comment by muak** [comment]
@candidodmv 
It's good!😄
Thanks.
